backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "services"
    label: "Services"
    folder: "content/_index/services-list"
    create: true
    fields:
      - {label: "Title" , name: "title" , widget: "string"}
      - {label: "Weight" , name: "weight" , widget: "number", valueType: "int"}
      - label: "Icon" 
        name: "asset" 
        widget: "object" 
        fields: 
        - {label: "Font Awesome Icon" , name: "icon" , widget: "string"}
        - {label: "Link" , name: "url" , widget: "string", required: false}
      - {label: "Text" , name: "body" , widget: "markdown"}